export interface LanguageConfig {
  code: string;
  name: string;
  readmeFileName: string;
}

export interface Translation {
  title: string;
  subtitle: string;
  copyright: string;
  viewInGallery: string;
  promptLibrary: string;
  modelPage: string;
  stats: string;
  totalPrompts: string;
  categories: string;
  previewVideos: string;
  lastUpdated: string;
  featuredPrompts: string;
  allPrompts: string;
  description: string;
  prompt: string;
  category: string;
  source: string;
  author: string;
  language: string;
  video: string;
  sourceLink: string;
  browseByCategory: string;
  localUsage: string;
  license: string;
  contribute: string;
  contributeDesc: string;
  autoGenerated: string;
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", readmeFileName: "README.md" },
  { code: "zh", name: "简体中文", readmeFileName: "README_zh.md" },
  { code: "zh-TW", name: "繁體中文", readmeFileName: "README_zh-TW.md" },
  { code: "ja-JP", name: "日本語", readmeFileName: "README_ja-JP.md" },
  { code: "ko-KR", name: "한국어", readmeFileName: "README_ko-KR.md" },
  { code: "th-TH", name: "ไทย", readmeFileName: "README_th-TH.md" },
  { code: "vi-VN", name: "Tiếng Việt", readmeFileName: "README_vi-VN.md" },
  { code: "hi-IN", name: "हिन्दी", readmeFileName: "README_hi-IN.md" },
  { code: "es-ES", name: "Español", readmeFileName: "README_es-ES.md" },
  { code: "es-419", name: "Español (Latinoamérica)", readmeFileName: "README_es-419.md" },
  { code: "de-DE", name: "Deutsch", readmeFileName: "README_de-DE.md" },
  { code: "fr-FR", name: "Français", readmeFileName: "README_fr-FR.md" },
  { code: "it-IT", name: "Italiano", readmeFileName: "README_it-IT.md" },
  { code: "pt-BR", name: "Português (Brasil)", readmeFileName: "README_pt-BR.md" },
  { code: "pt-PT", name: "Português", readmeFileName: "README_pt-PT.md" },
  { code: "tr-TR", name: "Türkçe", readmeFileName: "README_tr-TR.md" },
];

const en: Translation = {
  title: "Awesome Happy Horse 1 Prompts",
  subtitle: "A curated collection of Happy Horse 1 prompts sourced from the AtlasCloud prompt ecosystem.",
  copyright: "All prompts are shared for educational and discovery purposes. Open an issue if anything should be removed.",
  viewInGallery: "View in AtlasCloud",
  promptLibrary: "Prompt Library",
  modelPage: "Model Page",
  stats: "Statistics",
  totalPrompts: "Total Prompts",
  categories: "Categories",
  previewVideos: "Preview Videos",
  lastUpdated: "Last Updated",
  featuredPrompts: "Featured Prompts",
  allPrompts: "All Prompts",
  description: "Description",
  prompt: "Prompt",
  category: "Category",
  source: "Source",
  author: "Author",
  language: "Language",
  video: "Video",
  sourceLink: "Source Link",
  browseByCategory: "Browse by Category",
  localUsage: "Local Usage",
  license: "License",
  contribute: "How to Contribute",
  contributeDesc: "Submit a GitHub issue with a complete prompt, category, and preview URL. After approval, the workflow syncs it into the dataset.",
  autoGenerated: "This README is auto-generated.",
};

const zh: Translation = {
  title: "Happy Horse 1 提示词大全",
  subtitle: "基于 AtlasCloud 提示词生态整理的 Happy Horse 1 精选视频提示词仓库。",
  copyright: "所有提示词仅用于学习、整理和检索。如有内容需要移除，请提交 issue。",
  viewInGallery: "在 AtlasCloud 查看",
  promptLibrary: "提示词库",
  modelPage: "模型页",
  stats: "统计数据",
  totalPrompts: "提示词总数",
  categories: "分类数",
  previewVideos: "预览视频数",
  lastUpdated: "最后更新",
  featuredPrompts: "精选提示词",
  allPrompts: "全部提示词",
  description: "描述",
  prompt: "提示词",
  category: "分类",
  source: "来源",
  author: "作者",
  language: "语言",
  video: "视频",
  sourceLink: "原始链接",
  browseByCategory: "按分类浏览",
  localUsage: "本地使用",
  license: "许可证",
  contribute: "如何贡献",
  contributeDesc: "通过 GitHub Issue 提交完整提示词、分类和预览视频链接，审核通过后会自动同步到数据集。",
  autoGenerated: "此 README 为自动生成。",
};

const zhTW: Translation = {
  ...zh,
  title: "Happy Horse 1 提示詞大全",
  subtitle: "基於 AtlasCloud 提示詞生態整理的 Happy Horse 1 精選影片提示詞倉庫。",
  copyright: "所有提示詞僅用於學習、整理和檢索。如有內容需要移除，請提交 issue。",
  stats: "統計資料",
  totalPrompts: "提示詞總數",
  categories: "分類數",
  previewVideos: "預覽影片數",
  lastUpdated: "最後更新",
  featuredPrompts: "精選提示詞",
  allPrompts: "全部提示詞",
  description: "描述",
  prompt: "提示詞",
  category: "分類",
  sourceLink: "原始連結",
  browseByCategory: "按分類瀏覽",
  localUsage: "本地使用",
  license: "許可證",
  contribute: "如何貢獻",
  contributeDesc: "透過 GitHub Issue 提交完整提示詞、分類和預覽影片連結，審核通過後會自動同步到資料集。",
  autoGenerated: "此 README 為自動生成。",
};

const translations: Record<string, Translation> = {
  en,
  zh,
  "zh-TW": zhTW,
};

export function t<K extends keyof Translation>(key: K, locale: string): Translation[K] {
  const translation = translations[locale] || translations.en;
  return translation[key];
}
